name: Deploy no GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Clonar o código
        uses: actions/checkout@v4

      - name: Configurar GitHub Pages
        uses: actions/configure-pages@v4

      - name: Fazer deploy
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./

      - name: Publicar no GitHub Pages
        uses: actions/deploy-pages@v4
